services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    ports:
      - "5678:5678"
    networks:
      - n8n-network
    volumes:
      - ./shared:/data/shared
      - n8n-data:/home/node/.n8n
    environment:
      - "N8N_BLOCK_FILE_ACCESS_TO_N8N_FILES=false"
      - "N8N_RESTRICT_FILE_ACCESS_TO=/data/shared"
      # Since n8n requires credentials (this is for a hackathon, so security really doesn't matter):
      # Email: hackathon@build4good.com
      # Password: Building4Good

  browserless:
    image: browserless/chrome:latest
    ports:
      - "3000:3000"
    networks:
      - n8n-network
    environment:
      - "PREBOOT_CHROME=true"
      - "MAX_CONCURRENT_SESSIONS=5"
      - "DEFAULT_BLOCK_ADS=true"
      - "DEFAULT_BLOCK_TRACKERS=true"

networks:
  n8n-network:
    driver: bridge

volumes:
  n8n-data:
    driver: local
